import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { UserButton } from "@clerk/nextjs";

export default function Home() {
  const { data } = api.essays.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <header>
          <UserButton />
        </header>
        <div className="text-lg">
          Learn more about Create T3 App, the libraries it uses, and how to
          deploy it.
        </div>
        <div>
          {data?.map((essay) => (
            <div key={essay.id}>{essay.content}</div>
          ))}
        </div>
      </main>
    </>
  );
}
